## Project Part 1

###Team members:
Arshiya Sawhney: as5476

Ijaz Ahmed Khan: ik2557

In [ ]:
import pandas as pd
import requests

First, trying to load in dataset using the API

In [ ]:
api_url = "https://data.elexon.co.uk/bmrs/api/v1/generation/actual/per-type?from=2024-01-01&to=2025-01-01&settlementPeriodFrom=1&settlementPeriodTo=48&format=json"

In [ ]:
generation_by_fuel = requests.get(api_url)
generation_by_fuel.text
generation_json = generation_by_fuel.json()
generation_data = generation_json['data']

In [ ]:
generation_data[0]

{'startTime': '2024-01-01T00:00:00Z',
 'settlementPeriod': 1,
 'data': [{'businessType': 'Solar generation',
   'psrType': 'Solar',
   'quantity': 352},
  {'businessType': 'Wind generation',
   'psrType': 'Wind Offshore',
   'quantity': 8032},
  {'businessType': 'Wind generation',
   'psrType': 'Wind Onshore',
   'quantity': 4278},
  {'businessType': 'Production', 'psrType': 'Other', 'quantity': 327},
  {'businessType': 'Production', 'psrType': 'Nuclear', 'quantity': 4668},
  {'businessType': 'Production', 'psrType': 'Fossil Oil', 'quantity': 0},
  {'businessType': 'Production', 'psrType': 'Fossil Gas', 'quantity': 4413},
  {'businessType': 'Production',
   'psrType': 'Fossil Hard coal',
   'quantity': 100},
  {'businessType': 'Production',
   'psrType': 'Hydro Run-of-river and poundage',
   'quantity': 673},
  {'businessType': 'Production',
   'psrType': 'Hydro Pumped Storage',
   'quantity': 268},
  {'businessType': 'Production', 'psrType': 'Biomass', 'quantity': 1701}]}

In [ ]:
pd.json_normalize(generation_data)

,startTime,settlementPeriod,data
0,2024-01-01T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
1,2024-01-02T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
2,2024-01-03T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
3,2024-01-04T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
4,2024-01-05T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
...,...,...,...
362,2024-12-28T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
363,2024-12-29T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
364,2024-12-30T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
365,2024-12-31T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
366,2025-01-01T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."

In [ ]:
df1 = pd.DataFrame(generation_data)
df1.head()
## need to check how to clean the dataset

,startTime,settlementPeriod,data
0,2024-01-01T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
1,2024-01-02T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
2,2024-01-03T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
3,2024-01-04T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."
4,2024-01-05T00:00:00Z,1,"[{'businessType': 'Solar generation', 'psrType..."

Since we are currently running into issues with the API, we have loaded in the dataset in as a csv for now.

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving bac410d3-8a3e-4c8d-9aad-617038c2e8f6.csv to bac410d3-8a3e-4c8d-9aad-617038c2e8f6.csv

In [ ]:
data = pd.read_csv("bac410d3-8a3e-4c8d-9aad-617038c2e8f6.csv")
data.head()

,Dataset,PublishTime,StartTime,SettlementDate,SettlementPeriod,FuelType,Generation
0,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,BIOMASS,3044
1,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,CCGT,16799
2,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,COAL,0
3,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,INTELEC,-302
4,FUELHH,2025-02-06T05:30:00Z,2025-02-06T05:00:00Z,2025-02-06,11,INTEW,-26